### ISSUE TITLE
Weird issues

### ISSUE THREAD

**Issue by yyewolf** [CWTesseract/CWTCore#2]
Values such as light_diameter and time won't change, after setting it it will go back to original for some reasons :/

**Comment by Andoryuuta** [comment]
There is a different reason for both of those variables.

For `time`, it is a matter of who owns the variable, the client or the server. When Cube World starts, it creates both a client and a server, then connect to itself (even in singleplayer mode). Because of this, you end up with two `cube::World` instances in memory. One at `game->world`, and the other at `game->host.host_world`. The host constantly sends it's `time` for the clients to use, so to change the time, you need to set `game->host.host_world.time_info.time`.

As for the `light_diameter`, the skill/stat values are constantly recalculated every game frame based on the equipment/artifacts you have, so it's not really feasible to change it unless you hook the code that is calculating it.

**Comment by yyewolf** [comment]
How hard would it be to hook the code that's calculating it ?

**Comment by Andoryuuta** [comment]
I think that depends on your experience using a disassembler and writing x86_64 assembly code. You would first need to find the code that is writing to that variable, then insert a JMP statement to jump to your assembly stub that would handle setting up the stack and calling your C function.  An example of this would be ChrisMiuchiz's modloader code : https://github.com/ChrisMiuchiz/Cube-World-Mod-Launcher/tree/master/CubeModLoader
